secret_key_base: ENV['CRYSTAL_CLEAR_SECRET_KEY']
port: 3000
name: crystal-clear-book-search

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password

host: 0.0.0.0
port_reuse: true
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: ENV["CRYSTAL_CLEAR_DB_URL"]
auto_reload: true

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.
